강원대 FE_4조 4주차 제출
kakao-tech-campus-2nd-step3/Team4_FE pull request #16
Opened 2024-09-27 11:04 UTC by seorinnn

- Login.tsx 파일에서 스타일 코드 분리
- Login UI 수정
- 일반회원 및 트레이너회원 회원가입 인터페이스 정의
- 회원가입 기능 구현
- 프록시 설정 추가

2024-09-27 17:09 UTC, yujo11 requested changes
안녕하세요 서린님 ~

한 주간 개발 진행하느라 고생 많으셨습니다. 프로젝트를 진행하면서 새로운 경험을 하시고 새로운 고민거리들을 만나면서 잘 성장하고 계신거 같아 보기 좋네요 ㅎㅎ

---


### 주석에 대한 질문

주석에 대해 질문을 남겨주셨는데 `src/pages/UserSignup.tsx`의 주석은 제가 느끼기에 조금 과해보이는 면이 있습니다. 언제 호출이 되는지, 어떤 동작을 하는지에 대한 설명이 대부분이고 그에 대한 설명은 주석이 없더라도 코드를 통해 자연스럽게 유추가 가능해보이기 때문인데요.

적절하게 남겨진 주석은 코드를 볼 때 도움이 되기도 하지만 과하게 많이 남겨진 주석은 오히려 코드를 읽어가는 흐름을 방해하기도 합니다. 코멘트로 남긴 내용 중 하나의 함수가 하나의 역할을 하도록 리팩터링을 해보시라고 말씀 드린 부분이 있는데요. 주석이 없더라도 이런 함수 분리를 통해 변수명을 가지게 하면서 이런 주석들도 많이 줄이실 수 있을거라고 생각해요.

예를 들어 `onSubmit` 함수의 아래 부분을 별도의 함수로 분리한다면

```tsx
    // JSON 데이터를 Blob으로 변환
    const jsonData = {
      email: formData.email,
      password: formData.password,
      name: formData.name,
      local: formData.local,
    };
    const jsonBlob = new Blob([JSON.stringify(jsonData)], {
      type: 'application/json',
    });
```

이런 형태로 만들어볼 수 있겠죠
```ts
const jsonToBlob = () => {
    const jsonData = {
      email: formData.email,
      password: formData.password,
      name: formData.name,
      local: formData.local,
    };

    return new Blob([JSON.stringify(jsonData)], {
      type: 'application/json',
    });
}
```

그렇다면 onSubmit에서도 아래처럼 사용이 가능해지면서 함수명으로 어떤 동작을 하는지 설명이 되기 때문에 주석이 더욱 필요 없어질거라고 생각합니다

```ts
  const jsonBlob = jsonToBlob()
```


### 보통 주석은 아래 2가지 경우에 많이 작성하게 되는거 같아요
1. 코드로는 설명하지 못 하는 배경에 대한 설명을 적을 때
2. 공통으로 사용되는 함수나 컴포넌트를 다른 사람이 보다 쉽게 사용하도록 할 때


### 1. 코드로는 설명하지 못 하는 배경에 대한 설명을 적을 때

상황을 하나 가정해서 서린님이 만드는 서비스를 16세 이상만 가입 시킨다고 했을 때 아래와 같은 방어로직이 추가 될거에요

```ts
if (age < 16) {
   alert("16세 이상만 서비스 이용이 가능합니다")
   return;
}
```

코드를 통해 16세 이상만 가입이 가능하다는걸 알 수 있지만 "왜" 16세 이상만 가입이 가능한지는 코드로는 설명이 불가능한 부분인데요. 이럴 때 배경에 대한 주석을 남겨주면 코드를 보고 어떤 배경으로 이런 코드가 작성되었는지 알 수 있겠죠

```ts
// * ~~에서 ~~한 이유로 16세 이상만 회원가입을 허용함
if (age < 16) {
   alert("16세 이상만 서비스 이용이 가능합니다")
   return;
}
```

### 2. 공통으로 사용되는 함수나 컴포넌트를 다른 사람이 보다 쉽게 사용하도록 할 때

이 부분도 상황을 가정해서 트레이너로 가입하는 회원의 경우 사업자 등록번호를 받아야 하는 로직이 있다고 했을 때 유저가 숫자를 입력 했을 때 해당 숫자를 사업자번호 형식으로 변경해주는 유틸 함수를 만들 수 있을거에요

```ts
const stringToBizRegistrationNo = (value: string): string => {
  const numericValue = value.replace(/[^0-9]/g, '')

  if (numericValue.length > 5) {
    return `${numericValue.slice(0, 3)}-${numericValue.slice(3, 5)}-${numericValue.slice(5, 10)}`
  }

  if (numericValue.length > 3) {
    return `${numericValue.slice(0, 3)}-${numericValue.slice(3)}`
  }

  return numericValue
}
```

(꼭 주석이 필요할만한 로직은 아니지만) 이런 공통 함수의 경우에도 주석을 남겨주면 보다 쉽게 어떤 용도로 사용되고, 어떤 값을 넣었을 때 어떤 값을 반환받을 지 쉽게 알 수 있겠죠

```ts
/**
 * @description
 * - 입력 받은 사업자 등록번호를 정해진 형식으로 변환하여 반환합니다.
 * @example
 * - stringToBizRegistrationNo('1234567890') // '123-45-67890'
 */
export const stringToBizRegistrationNo = (value: string): string => {
  const numericValue = value.replace(/[^0-9]/g, '')

  if (numericValue.length > 5) {
    return `${numericValue.slice(0, 3)}-${numericValue.slice(3, 5)}-${numericValue.slice(5, 10)}`
  }

  if (numericValue.length > 3) {
    return `${numericValue.slice(0, 3)}-${numericValue.slice(3)}`
  }

  return numericValue
}
```

---

잘 작성 된 주석은 코드를 볼 때  많은 도움이 되지만 불필요한 주석들은 코드를 읽는 걸 방해하기도 하는데요. 꼭 주석이 필요한지 한번쯤 생각해보시면서 남겨보시는 것도 좋을거 같습니다 ㅎㅎ

---

ps) jsDoc 형식으로 주석을 남기면 아래처럼 IDE에서 쉽게 주석을 확인할 수 있으니 jsDoc도 잘 활용해보시면 좋겠네요 

<img width="854" alt="image" src="https://github.com/user-attachments/assets/55e676fc-410f-469a-b464-e761db654249">

---

고생 많으셨습니다 서린님~~ 👍 👍 👍

2024-09-27 17:09 UTC, yujo11 commented on src/pages/Signup/UserSignup.tsx
> +  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
submit 함수에서 많은 일들이 이뤄지고 있는데요. 내부 로직을 적절하게 분리해서 하나의 함수가 하나의 역할만 수행하도록 변경해보셔도 좋을거 같아요

2024-09-27 17:09 UTC, yujo11 commented on src/pages/Signup/UserSignup.tsx
> +  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
추가로 `onSubmit`이라는 이름으로는 어느 시점에 실행 되는지만 알 수 있는데요. 이런 이름보다는 함수가 실제로 수행하는 기능을 설명할 수 있도록 변경해보시면 좋을거 같네용

2024-09-27 17:09 UTC, yujo11 commented on src/pages/Signup/UserSignup.tsx
> +  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
이 함수도 마찬가지입니다!

2024-09-27 17:09 UTC, yujo11 commented on src/hooks/useSignup.ts
> +      }
`if-else` 문은 보통 명확한 참/거짓이 존재하는 상황에서 많이 사용하는데요.

지금 개발하고 계시는 어플리케이션의 특성상 `user`, `trainer`외에 다른 유형이 생길 가능성은 적어보이지만 Lookup Table이나 swich-case 문을 이용해서 실행되는 조건을 명확히 드러내도 좋을거 같아요

- ex)

```ts
swich (registerType) {
   'user':  
        await userSignup(formData);
        break;
    'trainer': 
        await trainerSignup(formData);
        break;
}
```

```ts
{
   'user': userSignup()
   'trainer': trainerSignup()
}[registerType]()
```

2024-09-27 17:09 UTC, yujo11 commented on src/api/auth/userSignup.ts
> +  }
statusCode가 `201`일 때 return 하는 `null`이 반환되어 사용되는 값으로 보이지는 않는데요. 사용되지 않는 값을 return 하는 대신 `201`이 아닐 때만 throw를 하게 해주셔도 좋을거 같아요

```suggestion
  if (response.status !== 201) {
    throw new Error('회원가입 실패');
  } 
```

2024-09-29 12:45 UTC, seorinnn commented
멘토님! 주말은 잘 보내셨나요?

4주차 코드리뷰는 원래 진행하지 않는 것이었는데 모르고 요청드려서 죄송합니다 😥
그럼에도 불구하고 코드리뷰 해주셔서 정말 감사드려요 ㅎㅎ 
이번주차 피드백도 정말 많은 도움 되었습니당 ☘

저도 `registerType`, `loginType` 조건문에서 `if else` 문을 쓰는 것이 괜찮은가? 라는 생각을 했었는데, 조건이 확실하게 드러나는 `switch` 문을 사용하는 것이 좋다는 의견을 주셔서 고민이 깨끗하게 해결되었습니다 ㅎㅎ

또한 
1. 일반회원 & 트레이너회원 회원가입
2. 일반회원 & 트레이너회원 로그인

위 기능들은 백엔드에서 서버 코드를 받아 연동되는 것까지 잘 확인하였습니다!

## 💻 4주차 코드리뷰 후 추가적으로 구현한 내용
- 하나의 함수가 하나의 역할만 수행하도록 분리
- 명확한 함수명으로 변경
- 불필요한 주석 삭제
- 회원가입 커스텀훅 `if else` 문에서 `switch` 문으로 변경
- 사용되지 않는 값 굳이 리턴하지 않도록 수정
- 비밀번호확인 불일치 시 회원가입 되는 문제 해결
- 회원가입 성공 시 로그인 페이지로 이동
- 일반회원 및 트레이너회원 로그인 기능 구현

2024-09-30 08:48 UTC, yujo11 approved these changes
고생 많으셨습니다 서린님 ~~ 이번 PR은 여기서 merge해도 좋을거 같네요 ㅎㅎ

api 사용하시는 모습을 보니 @tanstack/query 같은 라이브러리를 사용해보셔도 좋을거 같은데 한번 찾아보셔도 좋을거 같아요(반드시 적용하라는 얘기는 아닙니다!)

2024-09-30 08:48 UTC, yujo11 commented on src/api/auth/trainerLogin.ts
> +  if (response.status === 200) {
여기도 일관성 있게 status가 200이 아닐 떄 error를 trhwo하도록 변경해주셔도 좋을거 같네요

2024-09-30 08:48 UTC, yujo11 commented on src/api/auth/trainerLogin.ts
> +export const trainerLogin = async ({ email, password }: LoginData) => {
api를 정의한 함수의 경우 `post-` , `get-` 같은 prefix를 통해 역할을 드러내기도 하니 참고 하시면 좋겠네요

2024-09-30 08:48 UTC, merged