강원대 FE_4조 5주차 제출
kakao-tech-campus-2nd-step3/Team4_FE pull request #26
Opened 2024-10-04 11:35 UTC by seorinnn

## ❓ 멘토님께 질문하고 싶은 내용

## 💻 구현한 내용
- 로그인 성공 시 localStorage에 토큰 저장
- 로그인 전역 상태 관리 AuthContext 구현
- 로그인 상태에 따라 Header 다르게 구현
- 로그아웃 기능 구현
- 로그인한 회원 유형별로 홈화면 다르게 보여주는 기능 구현
- 일반회원 Profile 가져오는 커스텀훅 정의
- 일반회원 회원가입 시 우편번호 검색 기능 구현
- 일반회원 홈화면 프로필 띄우기
- 일반회원 PT 매칭하기 & 내 PT & 받은 제안 컴포넌트 생성

2024-10-05 09:55 UTC, yujo11 requested changes
안녕하세요 서린님 ~ 

이번 주는 코멘트 남길 내용이 많지 않았네요 소소한 코멘트들 남겼으니 확인해보시면 좋을거 같아요

>1. 로그인 후 홈화면으로 이동하는 navigate의 위치

저는 아래(마지막)에 위차하는걸 선호합니다.

코드를 읽을 때 사람은 자연스럽게 위에서 아래로 코드를 읽게 되는데요. 그렇기 때문에 로직이 동작하길 원하는 순서대로 작성하는게 맞다고 생각합니다. `localStorage`에 정보를 저장하고 `setAuth`함수가 실행되는 동작까지를 로그인으로 보고 그 이후에 홈 화면으로 이동하는게 더 자연스럽게 느껴지는거 같아요

>2. 스타일 코드 분리

저는 조금 번거롭더라도 style 함수는 분리하려고 하는편이기는 합니다 Style과 관련된 로직은 한 곳에 모아두고 싶기 때문인데요. 

이 부분은 서린님도 PR 본문에 적어주신 것처럼 정답은 없는 부분이라 상황에 따라 적절하게 판단해서 작업하시면 좋을거 같아요 ㅎㅎ

---

제가 남긴 피드백들이 조금이나마 서린님에게 도움이 되고 있는거 같아서 좋네요 ㅎㅎ 이번 주도 고생 많으셨습니다~~ 👍 👍 👍

2024-10-05 09:55 UTC, yujo11 commented on src/api/profile/getTrainerProfile.ts
> +  const response = await fetch('/api/trainers/profile', {
이건 그냥 궁금한건데 axios나 ky 같은 라이브러리를 사용하지 않고 `fetch` api 만 사용하시는 이유가 있을까요?

2024-10-05 09:55 UTC, yujo11 commented on src/components/Home/ReceivedOffers.tsx
> +          <StyledImage src={ReceiveOfferImage} alt='ReceiveOfferImage' />
스크린 리더기가 화면을 읽을 때 이미지라는걸 인지하고 있기 떄문에 alta태그에서 `Image`라는 텍스트는 제거해주셔도 될거 같아요

2024-10-05 09:55 UTC, yujo11 commented on src/components/Home/UserHomeProfile.tsx
> +            alt='프로필 이미지'
여기도 위와 같은 맥락으로 `이미지`라는 텍스트는 제거해주셔도 될거 같고, 한국인 사용자를 대상으로 하는거라면 alt 텍스트를 한국어로 통일해줘도 좋을거 같네요 ㅎㅎ

2024-10-05 09:55 UTC, yujo11 commented on src/hooks/useAuth.ts
> +  if (!context) {
방어로직 좋네요 ㅎㅎ 👍

2024-10-05 09:55 UTC, yujo11 commented on src/pages/Signup/UserSignup.tsx
> +  };
여기는 로직이 다소 복잡하게 구성되어 있고, 함수의 형태만 보고는 입/출력값을 예상하기 어려운데요. 조금 더 가독성을 높일 수 있는 방법을 고민해보시면 좋을거 같아요

2024-10-06 09:40 UTC, seorinnn commented on src/api/profile/getTrainerProfile.ts
> +  const response = await fetch('/api/trainers/profile', {
처음에 axios랑 fetch 중에 고민했었는데,
(step1, 2에서 사용했던 기술만 사용해야 한다는 규칙이 있었어서요!)
그렇게 복잡한 요청이나 여러 기능을 사용할 것이 아니라면 브라우저 내장 API인 fetch API를 쓰는 것이 좋겠다고 생각했습니다!
내장 라이브러리라서 따로 설치가 필요 없으니 용량도 크게 늘어나지 않으며, 추가적으로 해 줘야 하는 설정도 없다는 장점들도 있어 fetch를 사용하였습니다.

ky 라이브러리는 접해보지 못해서 멘토님의 질문을 보고 조금 찾아보았습니다. 새롭게 알게 되어 좋네용

2024-10-06 09:48 UTC, seorinnn commented on src/pages/Signup/UserSignup.tsx
> +  };
백엔드 쪽에서 추후에 지도 api를 사용하려면 우편번호가 필요하다고 하여 급하게 찾아보다가 `react-daum-postcode` 를 발견하여 아래 링크에 나온 예제 코드 그대로 사용하였습니다.

예제 코드가 있어 코드의 가독성을 크게 생각하지 않고 작성하였는데, 이런 경우에도 주로 코드를 수정하여 사용하나요?

(예제 코드가 주어지다보니 혹시나 함부로 건드리면 안될까봐서요 ,,
만약 상관없다면 어떻게 코드를 수정해야 좋을 지 바로 고민해보겠습니다!)

[https://www.npmjs.com/package/react-daum-postcode](url)

2024-10-06 11:05 UTC, seorinnn commented
주말은 잘 보내셨나요 😃
코멘트 달아주신 부분에 답글 달아두었습니다! 감사합니다 ㅎㅎ

## 새롭게 구현한 내용
- 트레이너 홈화면에 프로필 컴포넌트 추가
- Image 태그 alt 속성 한국어로 통일 및 수정
- 트레이너회원 홈화면에 내 고객 찾기 & 내 제안 기록 & 리뷰 보기 컴포넌트 추가

2024-10-06 11:06 UTC, seorinnn commented
> 주말은 잘 보내셨나요 😃 코멘트 달아주신 부분에 답글 달아두었습니다!
항상 수고가 많으십니다 감사합니다 ㅎㅎ
> 
> ## 새롭게 구현한 내용
> * 트레이너 홈화면에 프로필 컴포넌트 추가
> * Image 태그 alt 속성 한국어로 통일 및 수정
> * 트레이너회원 홈화면에 내 고객 찾기 & 내 제안 기록 & 리뷰 보기 컴포넌트 추가

2024-10-06 12:33 UTC, yujo11 commented on src/pages/Signup/UserSignup.tsx
> +  };
아하 그런 배경이 있었군요 이런 경우라면 코드를 볼 때 배경을 알 수 있게 주석으로 설명을 같이 남겨주시면 좋을거 같네요

2024-10-06 12:45 UTC, yujo11 approved these changes
고생 많으셨습니다 서린님~~ 👍 👍 👍

2024-10-06 12:45 UTC, yujo11 commented on src/pages/Signup/TrainerSignup.tsx
> +              <option value='FEMALE'>여성</option>
이런 값들은 enum이나 상수로 관리해보셔도 좋을거 같아요

2024-10-06 12:45 UTC, merged