강원대 FE_4조 6주차 제출
kakao-tech-campus-2nd-step3/Team4_FE pull request #39
Opened 2024-10-10 12:29 UTC by seorinnn

## 💻 구현한 내용
- 일반회원/트레이너회원 마이페이지 추가
- 헤더에서 ‘내정보’ 클릭 시 & 홈화면에서 프로필 클릭 시 마이페이지로 이동
- 일반회원 인바디이미지 등록 기능 구현
- 트레이너회원 경력 등록 기능 구현

## ❓ 멘토님께 질문하고 싶은 내용
1. `navigate` 호출 위치
저번 주차 코드리뷰에서도 `navigate`에 대하여 질문했었는데요.
약간 다른 질문이 또 생겨서 질문드려요!

현재 저는 페이지 컴포넌트 -> 관련 커스텀훅 -> api 함수 이와 같은 방향으로 api 함수를 호출하는데요.
(예를 들면 트레이너회원이 경력을 등록하는 경우엔 
`src/page/Career/RegisterCareer.tsx` -> `src/hooks/useCareer.ts` -> `src/api/career/postCareer.ts`)

회원가입, 로그인, 정보 입력 등등 api 함수를 호출하여 정보를 전송하고 나면 페이지를 이동시켜야 하는 경우가 많이 생깁니다. (ex: 경력을 등록하고 나면 마이페이지로 이동)
이런 상황에 `navigate`를 3가지 컴포넌트 중(페이지 컴포넌트, 관련 커스텀훅, api 함수) 어떤 컴포넌트에 두는 것이 좋을 지 고민이 됩니다!

현재 제 코드에서 경력을 등록하는 경우에는 페이지 컴포넌트`(src/pages/Career/RegisterCareer.tsx)`에서 `navigate`를 호출하고 있고,
로그인의 경우에는 `src/hooks/useLogin.tsx` 에서 `navigate`를 호출하고 있습니다.

전부 use~ 커스텀훅에서 호출하거나, api 함수에서 호출하도록 이 부분을 통일하는 것이 좋을 것 같아서, 주로 어떤 컴포넌트에서 `navigate`를 호출하는지 결정하고 통일하고 싶습니다!

---
안녕하세요 멘토님 ㅎㅎ
항상 열심히 피드백 해주시는 덕분에 발전하고 있다고 느낍니당 😊

이번 주차도 잘 부탁드립니다 매번 정말 감사드려요!

2024-10-12 09:06 UTC, yujo11 requested changes
안녕하세요 서린님 ~~ 발전한다고 느끼고 계신다니 저도 뿌듯하고 좋네요 ㅎㅎ

>navigate 호출 위치

말씀해주신 부분들이 각각 어떤 역할을 하고 있는지를 생각해보면 좋을거 같아요

api 는 어떤 역할을, 페이지 컴포넌트는 어떤 역할을, 커스텀훅은 어떤 역할을 하고 있는지 고민해보시고 어떤 위치에 들어가면 좋을지 서린님이 먼저 고민하고 생각해 주신 내용을 적어주시면 제 의견도 덧붙여보도록 하겠습니다 ㅎㅎ

이번 주도 고생 많으셨습니다 !!

2024-10-12 09:06 UTC, yujo11 commented on src/api/bodyInfo/postBodyInfo.ts
> +  });
이 부분의 코드가 반복되고 있는거 같은데요 추상화를 통해 중복되는 코드를 줄여보는 방법을 고민해봐도 좋을거 같습니다

2024-10-12 09:06 UTC, yujo11 commented on src/components/Home/TrainerHomeProfile.tsx
> +    <Wrapper onClick={handleProfileClick} style={{ cursor: 'pointer' }}>
`Wrpper`는 이미 `styled`로 정의 된 컴포넌트로 보이는데요. 

`Wrapper`에 `style을 정의하지 않고 여기에 추가로 `style` prop을 사용하는 이유가 있을까요?

2024-10-12 09:06 UTC, yujo11 commented on src/components/MyPage/Profile/TrainerMyPageProfile.tsx
> +  }
`<Suspense>`를 이용해 보시는 것도 고려해보시면 좋을거 같아요

2024-10-12 09:06 UTC, yujo11 commented on src/hooks/useBodyInfo.ts
> +      return false;
여기에서 반환하는 `boolean` 값은 어떤 용도로 사용되나요?

2024-10-12 09:06 UTC, yujo11 commented on src/components/MyPage/Profile/UserMyPageProfile.tsx
> +  }
내용을 보면 loading 중일 때의 처리처럼 보이는데 실제 판별은 `profile`이 존재하는지 여부로 하고 있어 조금 어색하게 느껴지는거 같아요. loading 상태일 때와 에러 상태일 때를 나눠서 처리해보셔도 좋을거 같아요

2024-10-12 09:06 UTC, yujo11 commented on src/pages/MyPage/TrainerMyPage.styles.ts
> +  color: #f5f5f5;
이런 색상들은 한 군데에 모아서 변수 등으로 관리하면 전체 애플리케이션에 일관 된 스타일을 적용하는데 도움이 될거 같네요

2024-10-12 09:06 UTC, yujo11 commented on src/pages/Signup/UserSignup.tsx
> +  // react-daum-postcode 예제 코드 사용
소소하게 참고할 수 있는 링크도 주석으로 같이 남겨주시면 좋을거 같네요 ㅎㅎ

2024-10-13 11:58 UTC, seorinnn commented on src/components/Home/TrainerHomeProfile.tsx
> +    <Wrapper onClick={handleProfileClick} style={{ cursor: 'pointer' }}>
급하게 추가하다보니 미처 생각못하고 style prop으로 추가한것 같습니다!
바로 수정하였습니다 ㅎㅎ

못 보고 넘어갈 뻔 했는데 말씀해주셔서 감사합니당

2024-10-13 12:25 UTC, seorinnn commented on src/hooks/useBodyInfo.ts
> +      return false;
코드를 확인해보니 불필요하게 return 문이 사용된 것 같습니다!

`useBodyInfo.ts` 뿐만 아니라 `useCareer.ts` 에서도 불필요하게 사용되고 있어서 두 커스텀훅에서 return문을 삭제하였습니다!

2024-10-13 12:42 UTC, seorinnn commented on src/pages/MyPage/TrainerMyPage.styles.ts
> +  color: #f5f5f5;
사실 전부터 몇 가지 색상들을 변수로 관리 해야지 해야지 미루다가 ..
결국 멘토님 피드백 보고 바로 주요 색상들 먼저 변수로 만들었습니당 ㅎㅎ

2024-10-13 13:23 UTC, seorinnn commented
### 1. navigate에 대하여
api 함수, 커스텀훅, 페이지 컴포넌트가 각자 어떤 역할을 담당하고 있는지 생각해보고 간단하게 정리해보았습니다!

**api 함수**
- 서버와 통신하는 역할을 집중적으로 함.
- 데이터를 가져오거나 전송하는 로직이 포함됨.

**커스텀훅**
- 페이지 컴포넌트가 api 호출을 쉽게 사용할 수 있도록 처리하는 역할을 함.

**페이지 컴포넌트**
- UI의 핵심 부분을 담당하며 화면에 필요한 데이터나 상태를 렌더링함.
- 사용자의 입력을 받아 적절한 액션을 트리거함.

이렇게 각자의 역할을 정리해보고 나니,  `navigate`는 페이지 이동을 처리하기 때문에 **페이지 컴포넌트**에서 호출하는 것이 맞다는 생각이 들었습니다!

말씀해주신대로 멘토님의 의견도 공유해주시면 바로 반영하여 코드를 수정하겠습니당

---
### 2. Error, Loading 처리에 대하여
개발을 시작하기 전에 일단 '우선순위가 낮은 것' 들을 생각해보았었는데,
그 중에 하나가 로딩과 에러 처리였습니다 😅

```
if (!profile) {
    return <p>프로필 정보를 불러오는 중...</p>;
  }
```

그래서 이 부분도 조금 무심하게 넘긴 것 같습니다 ..

또한 제가 아직 로딩, 에러 처리, Suspense 등 에 대해 제대로 공부해 본 적이 없는 상태인지라,
이 부분에서 시간을 미리 쓰는 것보다는 필수적인 기능들(아직 많이 남아있는 ...) 을 우선적으로 개발하고, 그 이후에 로딩과 에러 처리 등을 공부하면서 구현하는 것이 좋겠다고 생각했는데 혹시 그렇게 해도 괜찮을까요?

2024-10-14 02:10 UTC, seorinnn commented on src/api/bodyInfo/postBodyInfo.ts
> +  });
멘토님의 이 피드백 이후 현재 추상화 코드 작성 중입니다!
그 과정에서 백엔드랑 response 타입에 대하여 논의해야하는 부분이 생겨서 논의 중에 있습니당

이번 주차 코드 리뷰 전까지 api 함수를 추상화하여 중복되는 코드를 줄여보겠습니다!

2024-10-14 08:54 UTC, yujo11 approved these changes
안녕하세요 서린님~

소소한 코멘트 추가로 남겼으니 같이 확인해주시면 좋을거 같아요

---

>1. navigate에 대하여

정답은 없는 부분이지만 지금의 구조에서 적절하게 판단하신거 같아요

조금 첨언하면 프론트엔드 개발을 진행할 때 자주 변경되는 UI와 자주 변경되지 않는 비지니스(도메인) 로직을 분리하기도 하는데요. 이 경우에는 Custom Hook을 정의해서 도메인 로직을 모두 Hook 안에 구현하고, 컴포넌트는 Hook을 통해 도메인 로직을 주입 받아 UI 에 그리는 역할만 담당하게 되는데요.

이 경우에는 아래처럼 레이어가 생길거 같아요

- api (서버와 통신)
---
- 커스텀 훅(도메인 로직)
---
- 컴포넌트(UI 로직)

만약 위와 같은 구조로 코드를 작성한다면 도메인 로직을 담당하는 커스텀 Hook에서 navigate를 처리하는게 적절할거 같아요. 정답은 없으니 현재 서린님 구조에 맞는 방법을 적용하시면 좋을거 같네요

>2. Error, Loading 처리에 대하여

네 우선순위에 맞게 개발을 진행하시는 건 아주 좋습니다 👍 

Error 핸들링이나 로딩에 대한 처리 등은 프론트엔드 개발을 하시면 앞으로도 많이 고민을 하시게 될 영역이라 후순위로 미루더라도 이번 프로젝트에 꼭 한번 적용해보시면 좋겠네요



>3. key 에러

적어주신 내용을 보면 key값을 잘 주고 계신거 같은데 저도 원인을 잘 모르겠네요

혹시라도 infoId 중 중복되는 값이 있는 경우 해당 에러 메세지가 발생할 수 있는데 서버에서 내려오는 값 중에 중복되는 값이 있는지 한번 확인해보시면 좋을거 같습니다

---


이번 주도 고생 많으셨습니다~ 👍 👍 👍

2024-10-14 08:54 UTC, yujo11 commented on src/api/index.ts
> +export const fetchAPI = async ({
👍 👍 👍

2024-10-14 08:54 UTC, yujo11 commented on src/api/index.ts
> +export const fetchAPI = async ({
조금 더 추상화해서 아래와 같은 형태로 사용할 수 있어도 좋을거 같네요 ㅎㅎ
```
fetchAPi.get( ... )
fetchAPi.post( ... )
```

2024-10-14 08:54 UTC, yujo11 commented on src/styles/colors.ts
> +};
👍 👍 👍

2024-10-14 08:54 UTC, merged