강원대 FE_4조 3주차 제출
kakao-tech-campus-2nd-step3/Team4_FE pull request #4
Opened 2024-09-20 10:25 UTC by seorinnn

2024-09-21 08:50 UTC, yujo11 requested changes
안녕하세요 서린님 ~ 만나서 반갑습니다 ~

>이렇게 프로젝트의 처음부터 끝까지 모든 것을 제대로 겪어본 적이 없어서 카테캠 step2에서의 예시 코드를 많이 참고하게 됩니다 ㅠㅠ
파일 구조나 코드 스타일을 유사하게 작성하게 되는데,
현재 step2 코드를 많이 참고한 제 코드의 파일 구조나 코드 스타일에 조언을 주실 부분이 있는지 궁금합니다!
(step2 코드와 같이 tsx 파일에 스타일 코드를 작성하고 있는데, 이러한 방식이 문제가 없는지도 궁금합니다!)

지금 현재 상태는 나쁘지 않다고 생각합니다. 아직 코드가 많이 작성되지 않아 이 부분은 개발이 어느정도 더 진행 된 이후에 한번 더 얘기를 나눠보면 좋을거 같네요.

코멘트로 `SignupType`과 `Signup-` 페이지들이 연관되어 있으니 같이 둬도 좋겠다고 남겼는데요.  여기에 조금 첨언하면 지엽적으로 어떤 모듈이 사용되는 경우(ex - 로그인 페이지에서만 사용되는 컴포넌트가 존재) 파일을 선언하는 위치와 사용하는 위치를 물리적으로(파일트리 상으로) 가깝게 위치하도록 해보시면 유지보수하기 좋아 추천 드리고 싶습니다!

```
ex) 
- Login/ 
    - LoginPage.tsx
    -  components/
        -  EmailInput.tsx  
```

>(step2 코드와 같이 tsx 파일에 스타일 코드를 작성하고 있는데, 이러한 방식이 문제가 없는지도 궁금합니다!)

이 부분이 무슨 얘기인가 했는데 코드를 보고 이해를 했네요 ㅎㅎ 개인의 스타일에 따라 달라지는 부분이라 저는 문제가 되지는 않는다고 생각 하는데요. 다만 컴포넌트에 비지니스 로직이 들어오고, 파일이 커지면서 하나의 파일이 너무 길어지는 경우(N백줄 이상 되는 경우) 코드를 보기 불편할거 같다는 생각도 조금 드네요. 현재는 단순한 형태의 스타일 컴포넌트들만 존재하지만 후에 styled component에서 변수를 받아 분기 처리를 하는 등 보다 복잡해지는 경우에서는 더더욱 그럴거 같구요

>회원가입 기능 이외에도 많은 부분에서 서버 API를 이용해야 하는데,
백엔드와 연동 전, API를 이용해야 하는 모든 부분을 MSW를 사용해 이와 같이 하나하나 코드를 작성하여 Mock API를 만들어 확인해야 하나요?
Mock API를 만드는 것에도 꽤 많은 시간을 소요하게 될 것 같아 이러한 방식이 맞는지 궁금하여 질문드립니다.
조금 더 간편한 방법이 있는지도 궁금합니다!

msw 같은 라이브러리를 이용해서 Mock API를 작성하게 되면 서버에 의존하지 않고 API 요청까지 테스트 해볼 수 있다는 장점이 있는데요. 반드시 모든 부분을 Mocking 해서 사용할 필요는 없다고 생각합니다. 특히 지금처럼 프론트엔드 리소스가 백엔드 리소스보다 상대적으로 적은 경우라면 리소스는 한정 되어 있기 때문에 리소스를 보다 효율적으로 사용해야 하는데요. 

필요한 경우가 아니라면 서버 쪽과의 커뮤니케이션을 통해 지면 별 개발순서를 정해두고 서버 API 개발이 완료된 지면부터 실제 API를 호출하면서 개발을 진행하시는 것도 좋은 방법이라고 생각합니다.

>백엔드에서는 이 두 유형을 user(일반회원), Trainer(트레이너회원) 으로 명칭을 나누었다고 하는데,
제 생각에 user 라는 명칭은 모든 회원을 통틀어서 말할 때(예를 들면 저희 프로젝트에서는 일반회원과 트레이너회원을 통틀어서) 사용되는 것 같다는 생각이 들었습니다..
혹시 멘토님께서는 일반회원의 명칭을 어떻게 하는 것이 좋을 것 같은지 의견을 주실 수 있으실까요??

이런 네이밍에 해당하는 부분이 참 어려운데요. 이 부분은 저도 뾰족하게 좋은 의견이 바로 떠오르지 않네요. 

이런 부분은 앞으로 백엔드와 소통에서도 계속 활용 될 도메인과 관련된 용어이기 때문에 프론트, 백엔드 각각 다른 명칭으로 이런 일반회원과 트레이너를 칭하면 커뮤니케이션 미스가 발생하기 쉬운데요. 팀 전체에서 용어에 대한 논의를 한번 더 거쳐서 확정하시는걸 추천 드리고 싶습니다.

---

프로젝트 진행 경험이 많지 않으신 거 같은데 혼자 진행하게 되어 이런저런 고민들이 많이 되실거 같아요. 코드리뷰나 멘토링 시간을 이용해서 궁금하신 부분들을 많이 해소하시면 좋을거 같고, 꼭 그 시간들이 아니더라도 진행하면서 고민되는 부분들이 있으면 언제든지 질문 주세요 ~

고생 많으셨습니다 ~~ 👍

2024-09-21 08:50 UTC, yujo11 commented on index.html
> +<html lang="en">
소소하게 여기도 신경써서 변경해보시면 좋겠네요 ㅎㅎ

2024-09-21 08:50 UTC, yujo11 commented on index.html
> +  </head>
급한 부분은 아니지만 `<head>` 안에 들어가는 meta 태그들도 적절하게 변경해주시면 좋을거 같습니다 ~

2024-09-21 08:50 UTC, yujo11 commented on vite.config.ts
오 vite를 사용하시는군요 ㅎㅎ 👍

2024-09-21 08:50 UTC, yujo11 commented on src/styles/README.md
README를 폴더별로 남겨주셨군요 새로 코드베이스에 들어와 작업하게 되는 경우 도움이 될거 같네요 ㅎㅎ 👍

2024-09-21 08:50 UTC, yujo11 commented on src/pages/SignupType/index.tsx
> +    <>
`Fragment`태그는 필요할 때만 사용해주시는게 코드의 의도를 전달하기 더 좋을거 같네요

2024-09-21 08:50 UTC, yujo11 commented on src/pages/SignupType/index.tsx
> +            <Link to='/signup/user'>
Path들을 상수화해두신걸 봤는데 상수를 사용하시면 좋을거 같아요

2024-09-21 08:50 UTC, yujo11 commented on src/components/Layout/Header.tsx
> +  z-index: 9999;
이런 z-index의 경우 프로젝트 규모가 커지면 어디에서 어떤 수치를 사용하고 있는지 한번에 확인하기가 어려워서 상수화 해서 사용하시는걸 추천드리고 싶네요 

ex) 

```ts
const Z_INDEX = {
  header: 900,
  modal: 1000
}
```

2024-09-21 08:50 UTC, yujo11 commented on package-lock.json
패키지 매니저도 다양하게 존재하고 각각 특성을 가지고 있는데요. 이런 부분도 한 번 알아보고 넘어가셔도 좋을거 같아요 ㅎㅎ (npm을 사용하지 말라는 얘기는 아닙니다)

아래 글에 정리가 깔끔하게 되어 있어 한번 읽어보시길 추천 드립니다 ㅎㅎ

- [패키지 매니저의 과거, 토스의 선택, 그리고 미래](https://toss.tech/article/lightning-talks-package-manager)

2024-09-21 08:50 UTC, yujo11 commented on src/components/Layout/Header.tsx
> +export const Wrapper = styled.header`
이 `Wrapper`는 다른 곳에서 사용하고 있어서 `export` 해주고 계신걸까요?

2024-09-21 08:50 UTC, yujo11 commented on src/components/Layout/Header.tsx
> +export const Wrapper = styled.header`
style 파일들을 별도로 분리하는 방법 대신에 한 파일에 다 같이 작성 하신 이유가 있을까요?

2024-09-21 08:50 UTC, yujo11 commented on src/components/Layout/Header.tsx
> +`;
emotion으로 정의한 styled component 중에 어떤 건 `Styled-` prefix가 붙어있어 emotion으로 정의한 컴포넌트라는걸 쉽게 인지 할 수 있는데요. 다른 컴포넌트들에도 일정한 prefix를 붙여서 외부에서 import 해오는 컴포넌트와 style만 정의한 컴포넌트를 구분할 수 있게 해보셔도 좋을거 같아요

ex)

```tsx
<Card> // <- 외부에서 가져온 컴포넌트
  <_Container> // <- 스타일만 정의한 컴포넌트는 `_` prefix를 사용하여 구분
     // ...
  </_Container>
</Card>
```

2024-09-21 08:50 UTC, yujo11 commented on src/pages/SignupType/index.tsx
SignupType이라는 페이지명을 보고 어떤 유형의 회원으로 가입할 지 선택하는 페이지라는걸 바로 인지하지 못 헀는데요. 조금 더 직관적인 파일명을 고려해보셔도 좋을거 같아요

2024-09-21 08:50 UTC, yujo11 commented on src/pages/SignupType/index.tsx
폴더구조에서도 `SignupType` 페이지에서 `TrainerSignup`이나 `UserSignup` 페이지로 이동하게 되는만큼 연관되어 있는 페이지들을 같은 폴더로 묶어주셔도 좋을거 같네요

2024-09-22 06:48 UTC, seorinnn commented on src/components/Layout/Header.tsx
> +export const Wrapper = styled.header`
코드의 길이가 길지 않아 오히려 하나의 파일에 함께 작성하는 것이 편하다고 생각하여 그렇게 하였습니다. 

하지만 이후 코드의 길이가 길어질수도 있고 추후에 규모가 큰 프로젝트를 진행할 때를 미리 대비하여 style 파일을 분리하는 방식으로 수정하려고 합니다!

2024-09-22 06:53 UTC, seorinnn commented on src/components/Layout/Header.tsx
> +`;
```
export const Wrapper = styled.header`
  display: flex;
  align-items: center;
  justify-content: space-between;
  z-index: 9999;
  width: 100%;
  max-width: 100vw;
  height: ${HEADER_HEIGHT};
  padding: 0 16px;
  background: #eee;
`;

const UserWrapper = styled.div`
  display: flex;
  align-items: center;
`;

const StyledChatIcon = styled(ChatIcon)`
  margin-right: 65px;
`;

const Logo = styled.img`
  height: 30px;
  margin: 0 0 0 16px;
`;

const StyledLink = styled(Link)`
  font-size: 12px;
  margin: 0 5px;
  text-decoration: none;
  color: black;
`;
```

현재 저는 

- 다른 컴포넌트들을 `div` 태그로 감싸는 스타일을 정의한 `~Wrapper` 컴포넌트들
- 외부에서 import 해 온 `ChatIcon`의 스타일을 정의한 `StyledChatIcon` 컴포넌트
- 외부에서 import 해 온 `Link`의 스타일을 정의한 `StyledLink` 컴포넌트
- `img` 태그의 스타일을 정의한 `Logo` 컴포넌트

이렇게 스타일과 관련된 4가지 종류의 컴포넌트들이 있는 상황입니다. 
일정한 `prefix`를 붙이는 것을 권장해주신 멘토님의 말씀대로라면 `Wrapper`, `UserWrapper` 와 같은 `~Wrapper` 컴포넌트의 명칭도 다른 컴포넌트들과 동일하게 `StyledDiv` 로 바꾸고, `Logo` 컴포넌트의 명칭도 `StyledImg` 로 바꾸는 것이 좋을 것 같다는 게 맞나요?? 

제가 정확하게 이해한 것이 맞는지 궁금하여 재질문드립니다!!

2024-09-22 06:53 UTC, seorinnn commented
멘토님!
혹시 이번 리뷰가 끝나면 제가 이 pr을 머지하고, 피드백 받은 내용은 다른 브랜치에서 수정하여 반영하면 되는건가용?

2024-09-22 07:41 UTC, yujo11 commented on src/components/Layout/Header.tsx
> +`;
서린님 나름의 규칙을 가지고 작성하고 계셨군요 ㅎㅎ

제가 남긴 리뷰에서 의도한대로라면 `Styled-` prefix를 통해 일관되게 변수명을 통일해주는 것이 맞기는 한데요. 다만 `-Logo` 처럼 이름으로 의도를 유추할 수 있는 변수를 `-Img`처럼 이름에서 의도를 유추할 수 없는 이름으로 변경하는 것은 반대하고 싶네요. prefix를 붙이는건 여전히 추천 드리고 싶구요

추가로 이번 리뷰도 그렇고 앞으로의 리뷰들도 그렇고 저의 의견을 전달드리는 것일 뿐 최종적인 결정은 서린님이 하셔야 하는데요. 제가 리뷰로 남긴 내용들이 절대 정답이라고 생각하지 마시고 이런 의견도 있다고 생각해주시면 좋을거 같습니다 ㅎㅎ

2024-09-22 07:42 UTC, yujo11 commented
@seorinnn 님 이 branch에 이어서 피드백 내용을 반영해주시면 자동으로 PR에 반영되기 때문에 현재 PR 보내주신 브랜치에 이어서 수정하신 내용들 남겨주시면 됩니다!

2024-09-22 10:51 UTC, seorinnn commented
피드백 주셨던 부분들 수정하였습니다!

사실 생각보다 고쳐야 할 부분이 많다고 느껴져서 조금 막막했는데,
막상 하나씩 수정하다보니 코드가 다듬어진 것 같고, 더 올바른 방향으로 나아가게 된 것 같아서 재밌었습니당
성장한 것 같은 기분도 들어서 뿌듯했습니다 😄
(아직은 별 거 없지만요.. ㅎㅎ)

또 저 혼자서는 생각도 못 했던 부분들을 짚어주셔서 좋았고 어떤 부분들은 잘했다고 칭찬해주셔서 정말 좋았습니다 ㅎㅎ

꼼꼼하게 피드백 주셔서 감사합니다!
앞으로도 열심히 하겠습니다 ⭐

또 수정할 부분이 있으면 말씀해주세요! 3주차 수고많으셨습니다 🌱


(그리고 전에 깃허브 잔디에 대해서 질문 드렸었는데,
Master 브랜치에 merge 하는 순간 바로 전에 커밋했던 잔디들이 심어졌습니다 ㅎㅎ
Master 브랜치에 merge 해야만 Contribution activity 가 반영되며 잔디가 심어지는 것 같습니다!)

2024-09-22 14:03 UTC, yujo11 approved these changes
리뷰를 반영하면서 성장하는 느낌이 들었다니 좋은 신호네요 ㅎㅎ

이번 리뷰는 여기서 merge해도 좋을거 같아요

리뷰 반영하느라 고생 많으셨습니다 서린님 ~~ 👍 👍 👍

2024-09-22 14:03 UTC, yujo11 commented on .github/ISSUE_TEMPLATE/기능-관련-이슈.md
템플릿 활용 좋네요 ㅎㅎ

2024-09-22 14:03 UTC, yujo11 commented on index.html
👍 👍 👍 

meta 태그를 이용하면 링크 공유 시, 페이지의 thumbnail을 보여주는 등 다양한 기능을 추가로 할 수 있는데 이건 TODO 로 남겨두고 프로젝트 후반에 한번 적용해보셔도 좋을거 같아요

2024-09-22 14:03 UTC, yujo11 commented on src/components/Layout/Header.tsx
style 파일이 분리 되니 훨씬 깔끔해보이네요 ㅎㅎ 👍

2024-09-22 14:03 UTC, yujo11 commented on src/pages/Login/index.tsx
> +`;
여기도 일관성 있게 style 파일이 분리되면 좋겠네요 ㅎㅎ

2024-09-22 14:03 UTC, yujo11 commented on src/components/Layout/index.tsx
`index`라는 이름도 좋지만 개인적으로는 `Layout`처럼 명시적으로 쉽게 파악할 수 있는 파일명을 사용하는걸 선호하는데요. 이런 관점도 있으니 참고만 해주세요 ㅎㅎ

2024-09-22 14:03 UTC, yujo11 commented on src/styles/z-index.ts
> +  header: 900,
z_index는 1단위로 주는 것보다 100이나 10단위로 기준을 잡아두면 나중에 z_index를 사용하는 곳이 많아질 때 훨씬 쉽게 z_index를 적용할 수 있을거에요. 참고하시면 좋겠네요 ㅎㅎ

ex) 
- 초기
```ts
const Z_INDEX = {
   header: 100,
   modal: 500
}
```
- 이후 몇 개의 요소가 더 추가
```ts
const Z_INDEX = {
  header: 100,
  foo: 200,
  fooo: 210,
  bar: 300,
  modal: 500,
  snackbar: 510
}
```

2024-09-22 14:03 UTC, merged