강원대 FE_4조 10주차 제출
kakao-tech-campus-2nd-step3/Team4_FE pull request #67
Opened 2024-11-08 10:03 UTC by seorinnn

## 💻 구현한 내용
- getDisplayGender util 함수로 분리
- stomp 설치
- 일반회원 스케쥴 조회 기능 구현
- 트레이너회원 스케쥴 조회 기능 구현
- 일반회원 스케쥴 완료 기능 구현
- 트레이너회원 스케쥴 추가 기능 구현
- 채팅 관련 api 함수 정의

---
안녕하세요 멘토님! 
벌써 마지막 코드리뷰 주차가 되었네요 😥

2024-11-09 06:22 UTC, yujo11 requested changes
안녕하세요 서린님 ~ 

벌써 마지막 리뷰라니 시간이 정말 빠르네요 그동안 진행했던 리뷰가 서린님에게 도움이 되었다니 다행이네요

아쉬움이 남는 부분은 PR본문에 남겨주신 것처럼 프로젝트 끝나고 나서라도 챙기면서 학습해보시면 분명히 도움이 되실거라고 생각합니다 !

진행하시면서 어렵거나 궁금한 부분들이 있으면 언제든 편하게 물어봐주세요 ~

고생 많으셨습니다 서린님 ~~ 👍 👍 👍

2024-11-09 06:22 UTC, yujo11 commented on src/components/Home/LinkedClients.tsx
> +    navigate(RouterPath.trainerPtSchedule.replace(':ptId', ptId.toString()));
replace해서 특정 경로로 움직이는 경우는 util함수를 만들어서 사용하거나 path 자체에 replace기능을 넣어서 선언해봐도 좋을거 같네요

ex)

```tsx
const ReplacePath = {
   trainerPtSchedule: (ptId: number) => RouterPath.replcae(":ptId", ptId.toString())
}
```

2024-11-09 06:22 UTC, yujo11 commented on src/hooks/useSchedule.ts
> +      console.error('PT 일정 추가 실패:', error);
여긴 의도적으로 남기는 error 로그인가요?

2024-11-09 06:22 UTC, yujo11 commented on src/utils/getDisplayGender.ts
> +};
중첩된 삼항연산자는 코드를 보기 어렵게 만들어 지양되는 패턴 중 하나인데요. 가독성을 개선할 수 있는 방법을 고민해서 적용해보시면 좋을거 같습니다 ㅎㅎ

2024-11-09 06:22 UTC, yujo11 commented on src/hooks/usePtDetail.ts
hook으로 추상화해서 사용하는 형태 좋네요 ㅎㅎ 👍 👍 👍

2024-11-09 06:22 UTC, yujo11 commented on src/hooks/usePtDetail.ts
> +  }, []);
`ptId`가 변경되어도 이 hook이 반환하는 `ptDetail` 은 컴포넌트가 마운트 되는 시점의 정보에서 업데이트가 되지 않을거 같은데 의도하신 부분일까요?

2024-11-09 06:22 UTC, yujo11 commented on src/components/PtSchedule/UserProfile.tsx
> +  const numberPtId = ptId ? parseInt(ptId, 10) : 0;
String을 Number로 타입 변환하는 방법은 여러가지가 있는데 그 중 `parseInt`를 사용하신 이유가 있나요?

2024-11-10 13:14 UTC, seorinnn commented
월요일까지 피드백 반영하여 코드 수정하겠습니다 ㅠ
지금 남은 기능들 급하게 구현하고 있어서 잠시만 기다려주시면 감사하겠습니다 !!!

2024-11-11 10:24 UTC, yujo11 approved these changes
월요일까지 merge 해야돼서 일단 merge 해두겠습니다 ㅎㅎ

내일 멘토링 시간에 더 얘기 나눠보면 좋을거 같네요

고생 하셨습니다 ~~

2024-11-11 10:24 UTC, merged

2024-11-11 14:59 UTC, seorinnn commented on src/hooks/useSchedule.ts
> +      console.error('PT 일정 추가 실패:', error);
우선 에러가 난 경우 콘솔에 에러 로그를 남기는 방식으로 에러 처리를 구현하고,
추후 필수 기능 구현이 완료되면 에러를 어떻게 처리해야 하는 지 더 공부하여 수정하려고 했었습니다!

하지만 아직 기능 구현이 완료되지 않아서 에러 로그만 남겨둔 상황입니다 .. ㅠ

2024-11-11 15:03 UTC, seorinnn commented on src/hooks/usePtDetail.ts
> +  }, []);
그 부분 type(일반회원/트레이너회원 중 어떤 타입으로 로그인하였는지), ptId가 변경되면 fetchPtDetail() 이 실행되도록 수정해두었습니다!

2024-11-11 15:11 UTC, seorinnn commented on src/components/PtSchedule/UserProfile.tsx
> +  const numberPtId = ptId ? parseInt(ptId, 10) : 0;
사용법이 간단하다고 생각하여 `parseInt`를 사용하였는데, 더 찾아보니 `Number`도 간단하게 사용할 수 있네요!

멘토님께서는 String -> Number 타입 변환의 경우에 주로 어떤 방법을 사용하시나요??

2024-11-11 15:19 UTC, seorinnn commented on src/utils/getDisplayGender.ts
> +};
`switch-case` 문을 사용하는 방식으로 수정해두었습니다!
`switch-case` 문으로 수정하니 가독성이 개선된 것 같습니당 ㅎㅎ